#pragma once

#include "EditorBridge.h"

#include <QByteArray>
#include <QString>

class DotNetEditorBridge : public EditorBridge
{
public:
    DotNetEditorBridge();
    ~DotNetEditorBridge() override;

    bool openPath(const QString &path) override;
    bool savePath(const QString &path) override;
    bool hasSession() const override;
    bool selectSlot(const QString &key) override;
    bool setCurrentBox(int box) override;
    bool storageLayout(StorageLayout &out) const override;
    QByteArray slotPng(const QString &key) override;
    QString getField(const QString &name) override;
    bool setField(const QString &name, const QString &value) override;
    bool commitCurrent() override;
    bool legalityValid() const override;
    QString legalityReport(bool verbose) override;
    QString fieldChoices(const QString &name) override;
    QString previewShowdown(const QString &text) override;
    bool importShowdown(const QString &text) override;
    QString exportShowdown(const QString &scope) override;
    QByteArray exportEntity() override;
    QString entityFileName() override;
    bool importEntity(const QByteArray &data) override;
    QString slotPreview(const QString &key) override;
    QString slotCryPath(const QString &key) override;
    bool qrHasBoxSlotCopies() const override;
    QString exportQrMessage(int box, int slot, int copies) override;
    QByteArray exportQrPng(int box, int slot, int copies) override;
    bool importQrMessage(const QString &message) override;
    bool importQrPng(const QByteArray &png) override;
    bool writeCurrentToSlot(const QString &key) override;
    bool deleteSlot(const QString &key) override;
    bool swapSlots(const QString &source, const QString &destination) override;
    bool dropOnSlot(const QString &key, const QByteArray &data) override;
    bool needsClosePrompt() const override;
    bool needsOpenPrompt() const override;
    bool needsExportPrompt() const override;
    bool pathIsSave(const QString &path) override;
    bool saveUserConfig() override;
    bool exportBackup(const QString &path) override;
    bool saveEntityPath(const QString &path) override;
    QString suggestedBackupName() override;
    bool applyStartup(const QStringList &args) override;
    bool takeBackupPrompt() override;
    bool createBackupFolder() override;
    bool isExportable() const override;
    QString backupDirectory() override;
    QString inventoryDocument() override;
    QString inventoryModify(const QString &action, const QString &json) override;
    bool saveInventory(const QString &json) override;
    bool hasPokedex() const override;
    QString pokedexDocument() override;
    QString pokedexModify(const QString &action, const QString &json) override;
    bool savePokedex(const QString &json) override;
    bool cancelPokedex() override;
    bool hasAccessory() const override;
    QString accessoryDocument(const QString &page) override;
    QString accessoryPages() override;
    QString accessoryModify(const QString &action, const QString &json) override;
    bool saveAccessory(const QString &json) override;
    bool cancelAccessory() override;
    bool hasSaveBlock() const override;
    QString saveBlockDocument(const QString &page) override;
    QString saveBlockPages() override;
    QString saveBlockModify(const QString &action, const QString &json) override;
    bool saveSaveBlock(const QString &json) override;
    bool cancelSaveBlock() override;
    QString batchProperties() override;
    QString runBatch(const QString &scope, const QString &instructions) override;
    bool hasBox() const override;
    QString boxExportDocument() override;
    QString exportBoxes(const QString &destPath, const QString &json) override;
    bool saveBoxExportSettings(const QString &json) override;
    QString pkmDatabaseDocument() override;
    QString searchPkmDatabase(const QString &json) override;
    bool loadPkmDatabaseHit(int index) override;
    QString encounterDocument() override;
    QString searchEncounters(const QString &json) override;
    bool loadEncounter(int index) override;
    bool hasWondercards() const override;
    QString wondercardDocument() override;
    QString wondercardModify(const QString &action, const QString &json) override;
    bool saveWondercards(const QString &json) override;
    bool cancelWondercards() override;

private:
    using component_entry_point_fn = int (*)(void *arg, int arg_size_in_bytes);
    using close_fn = int (*)(void *context);

    bool call(component_entry_point_fn fn, const QString &path) const;
    QString readText(component_entry_point_fn prepare, const QString &key) const;

    QByteArray readBinary(component_entry_point_fn prepare) const;
    QByteArray readBinary(component_entry_point_fn prepare, const QString &key) const;

    void *_hostfxr{};
    void *_context{};
    close_fn _close{};
    component_entry_point_fn _openPath{};
    component_entry_point_fn _savePath{};
    component_entry_point_fn _hasSession{};
    component_entry_point_fn _selectSlot{};
    component_entry_point_fn _setCurrentBox{};
    component_entry_point_fn _getStorageLayout{};
    component_entry_point_fn _prepareSlotPng{};
    component_entry_point_fn _copyPreparedPng{};
    component_entry_point_fn _getField{};
    component_entry_point_fn _setField{};
    component_entry_point_fn _commitCurrent{};
    component_entry_point_fn _legalityValid{};
    component_entry_point_fn _prepareLegalityReport{};
    component_entry_point_fn _getChoices{};
    component_entry_point_fn _copyPreparedText{};
    component_entry_point_fn _previewShowdown{};
    component_entry_point_fn _importShowdown{};
    component_entry_point_fn _prepareShowdownExport{};
    component_entry_point_fn _prepareEntityCopy{};
    component_entry_point_fn _prepareEntityFileName{};
    component_entry_point_fn _importEntity{};
    component_entry_point_fn _slotPreview{};
    component_entry_point_fn _slotCryPath{};
    component_entry_point_fn _qrHasBoxSlotCopies{};
    component_entry_point_fn _prepareQrMessage{};
    component_entry_point_fn _prepareQrPng{};
    component_entry_point_fn _importQrMessage{};
    component_entry_point_fn _importQrPng{};
    component_entry_point_fn _writeCurrentToSlot{};
    component_entry_point_fn _deleteSlot{};
    component_entry_point_fn _swapSlots{};
    component_entry_point_fn _dropOnSlot{};
    component_entry_point_fn _needsClosePrompt{};
    component_entry_point_fn _needsOpenPrompt{};
    component_entry_point_fn _needsExportPrompt{};
    component_entry_point_fn _pathIsSave{};
    component_entry_point_fn _saveUserConfig{};
    component_entry_point_fn _exportBackup{};
    component_entry_point_fn _saveEntityPath{};
    component_entry_point_fn _prepareBackupName{};
    component_entry_point_fn _applyStartup{};
    component_entry_point_fn _takeBackupPrompt{};
    component_entry_point_fn _createBackupFolder{};
    component_entry_point_fn _isExportable{};
    component_entry_point_fn _prepareBackupPath{};
    component_entry_point_fn _prepareInventory{};
    component_entry_point_fn _inventoryModify{};
    component_entry_point_fn _saveInventory{};
    component_entry_point_fn _hasPokedex{};
    component_entry_point_fn _preparePokedex{};
    component_entry_point_fn _pokedexModify{};
    component_entry_point_fn _savePokedex{};
    component_entry_point_fn _cancelPokedex{};
    component_entry_point_fn _hasAccessory{};
    component_entry_point_fn _prepareAccessory{};
    component_entry_point_fn _prepareAccessoryPages{};
    component_entry_point_fn _accessoryModify{};
    component_entry_point_fn _saveAccessory{};
    component_entry_point_fn _cancelAccessory{};
    component_entry_point_fn _hasSaveBlock{};
    component_entry_point_fn _prepareSaveBlock{};
    component_entry_point_fn _prepareSaveBlockPages{};
    component_entry_point_fn _saveBlockModify{};
    component_entry_point_fn _saveSaveBlock{};
    component_entry_point_fn _cancelSaveBlock{};
    component_entry_point_fn _prepareBatchProperties{};
    component_entry_point_fn _runBatch{};
    component_entry_point_fn _hasBox{};
    component_entry_point_fn _prepareBoxExport{};
    component_entry_point_fn _exportBoxes{};
    component_entry_point_fn _saveBoxExportSettings{};
    component_entry_point_fn _preparePkmDatabase{};
    component_entry_point_fn _searchPkmDatabase{};
    component_entry_point_fn _loadPkmDatabaseHit{};
    component_entry_point_fn _prepareEncounterDatabase{};
    component_entry_point_fn _searchEncounters{};
    component_entry_point_fn _loadEncounter{};
    component_entry_point_fn _hasWondercards{};
    component_entry_point_fn _prepareWondercards{};
    component_entry_point_fn _wondercardModify{};
    component_entry_point_fn _saveWondercards{};
    component_entry_point_fn _cancelWondercards{};
};
